# Generated by Django 5.2 on 2025-04-18 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('difficulty_order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['difficulty_order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('prerequisite_topics', models.ManyToManyField(blank=True, to='aptitude.topic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TutorialPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(help_text='Display order (1-based)', validators=[django.core.validators.MinValueValidator(1)])),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation with LaTeX formulas like $$E=mc^2$$')),
                ('key_formulas', models.TextField(blank=True, help_text='Important formulas (auto-extracted from explanation)')),
                ('examples', models.JSONField(default=list, help_text="List of examples with structure: [{'problem':'...','solution':'...','analysis':'...','complexity':'Beginner/Intermediate/Advanced'}]")),
                ('common_pitfalls', models.TextField(blank=True, help_text='One pitfall per line')),
                ('quick_tricks', models.TextField(blank=True, help_text='One trick per line')),
                ('practice_advice', models.TextField(blank=True)),
                ('recommended_resources', models.TextField(blank=True, help_text='One resource per line')),
                ('is_miscellaneous', models.BooleanField(default=False, help_text="Check if this is a 'catch-all' part")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_parts', to='aptitude.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_parts', to='aptitude.topic')),
            ],
            options={
                'verbose_name': 'Tutorial Part',
                'verbose_name_plural': 'Tutorial Parts',
                'ordering': ['order'],
                'unique_together': {('topic', 'level', 'order')},
            },
        ),
    ]
