# Generated by Django 5.2 on 2025-04-18 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Which exam levels this topic belongs to', related_name='topics', to='aptitude.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='difficulty_order',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('ENTRY', 'Entry Level (Basic IT Jobs, Internships)'), ('PSU', 'PSU Exams (ONGC, BHEL, SAIL)'), ('GOVT', 'Government Exams (SSC, Banking)'), ('CAT', 'MBA Entrance (CAT, XAT)'), ('UPSC', 'UPSC/State PSC'), ('ADV', 'Advanced (Olympiads, Research)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, choices=[('quant', 'Quantitative Aptitude'), ('verbal', 'Verbal Ability'), ('logical', 'Logical Reasoning'), ('tech', 'Technical Knowledge')], max_length=50),
        ),
        migrations.AlterField(
            model_name='topic',
            name='prerequisite_topics',
            field=models.ManyToManyField(blank=True, related_name='is_prerequisite_for', to='aptitude.topic'),
        ),
    ]
