# Generated by Django 5.2 on 2025-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpart',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='Mark as complete for comprehensive tutorials'),
        ),
        migrations.AddField(
            model_name='tutorialpart',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Display order within the topic-level combination'),
        ),
        migrations.AddField(
            model_name='tutorialpart',
            name='quick_tips',
            field=models.TextField(blank=True, help_text='Shortcuts and memory aids'),
        ),
    ]
