# Generated by Django 5.2 on 2025-04-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Order in which this part should appear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_parts', to='aptitude.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_parts', to='aptitude.topic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'level', 'order')},
            },
        ),
    ]
